### PR TITLE
Cumulative fixes for Python 3 and modern linux support.

### PR DESCRIPTION
**Pull request by dobs**
Notably this should help resolve:

* Issues related to using `python` and `pycompile` rather than their Python 3 variants (see: https://github.com/PagerDuty/pdagent/issues/152).
* Updated HOWTO with new gnupg paths (see: https://github.com/PagerDuty/pdagent/issues/151).
* Issues attempting to install to `/lib/systemd/system` when not available.

The additions/deletions from `pd-queue`, `pd-send` and their `*.py` iterations are mostly just a copy, with a minor change in `pd-queue` to leverage `six`'s `iteritems`.

### CODE REVIEW

**Comment by dobs** [comment]
Current status: Testing on RHEL 8 and Ubuntu 18 and 20 to confirm it resolves reported issues.

**Comment by Gleland** [comment]
Hello! Is this work still being considered? I'm also affected by issue #152 and saw that this hasn't been updated in a while.

**Comment by bzmw** [comment]
Sorry @Gleland , we are currently working to replace this project with https://github.com/PagerDuty/go-pdagent so we should consider the PR abandoned. 

We left this open in case folks want to cherry-pick fixes from it.

**Comment by Gleland** [comment]
Thanks for the fast response, @bzmw ! Is there alternative documentation for the go instructions (other than the project's README)? For reference, I'm following these guides [0,1], which points to the python-based agent as the latest, and as being preferred over the perl agent.

[0] https://www.pagerduty.com/docs/guides/agent-install-guide/
[1] https://www.pagerduty.com/docs/guides/nagios-integration-guide/

**Comment by bzmw** [comment]
@Gleland currently there is not! We're actively working on update that documentation and more right now.

**Pull request closed without merging**
