### PR TITLE
Add a quick foreground flag.

### PR DESCRIPTION
**Pull request by cdegroot**
If we get more command line arguments, we need to add a proper
getopts setup, but for now this suffices.

Should satisfy https://github.com/PagerDuty/pdagent/issues/92

### CODE REVIEW

**Comment by divtxt** [comment]
Looks good.  I want to be stricter about the args but it's not worth more than one line at this time.

nit: skipping `daemonize` also skips the pid file check & writing, which preventing two agents from running and from using init script stop. not sure that's worth fixing at this time either. :)

**Comment by phlegx** [comment]
Has the "-f" flag be removed again from the master? 

For running it within docker and supervisor, one would need to run this in foreground.

**Comment by divtxt** [comment]
@phlegx  - we never merged the "-f" flag in master.

We're not planning an official release at this time.  You can use this branch or patch your agent install manually for this.

**Comment by spkane** [comment]
@divtxt Please consider merging this (or something similar). It is becoming much more common to be running Nagios in environments that use supervisors that need non-daemonizing processes. 

Trying to troubleshoot the issue, track down this PR, patch our build process, test, and iterate, is a lot more trouble for folks then applying something like this, and noting in the setup instructions that  this switch can be used for environments like supervisord and systemd that don't expect their processes to daemonize.

**Comment by mlewis033** [comment]
Implemented with #100

**Pull request closed without merging**
