### PR TITLE
Merge in changes from version 1.7.3

### PR DESCRIPTION
**Pull request by hcopperm**
https://github.com/PagerDuty/pdagent/pull/153/ was released but never merged. this pr currently includes the changes from https://github.com/PagerDuty/pdagent/pull/171 as well. 

Original description from pr 171:
## Description
We learned that a recent cert upgrade caused problems for some people who use pdagent. The changes in this pr accomplish the following

- [x] Certs are updated
- [x] Both the `ubuntu` and `centos` builds now run
- [x] If people want to run builds inside Docker (which does not support `systemd` although it technically exists), there is now a way to specify the correct option so that the packages can be Docker-compatible
- [x] Documentation is updated 
- [x] Update version number
- [x] Update tests so that they run in python3 (remove throttling testing)

Original description from pr 153:

Notably this should help resolve:

* Issues related to using `python` and `pycompile` rather than their Python 3 variants (see: https://github.com/PagerDuty/pdagent/issues/152).
* Updated HOWTO with new gnupg paths (see: https://github.com/PagerDuty/pdagent/issues/151).
* Issues attempting to install to `/lib/systemd/system` when not available.

The additions/deletions from `pd-queue`, `pd-send` and their `*.py` iterations are mostly just a copy, with a minor change in `pd-queue` to leverage `six`'s `iteritems`.

### CODE REVIEW

**Comment by joshwertheim** [comment]
Quick suggestion, can we add a user-agent to our urllib requests? Something like: https://stackoverflow.com/a/24226797

This way we can start tracking usage once this is finally deployed/released.

**Comment by hcopperm** [comment]
> Quick suggestion, can we add a user-agent to our urllib requests? Something like: https://stackoverflow.com/a/24226797
> 
> This way we can start tracking usage once this is finally deployed/released.

urg despite the fact that this is a very good idea i'm gonna leave it for if we end up investing more into pdagent

**Review by blagh — APPROVED** [review]
:shipit:

**Review by joshwertheim — APPROVED** [review]
🚀

**Pull request merged**
